### ISSUE TITLE
Update text on Contact Page

### ISSUE THREAD

**Issue by 3design** [3design/gbc#10]
- [ ] Contact page text taken from GBC website. This can be updated as needed 

# Contact the Global Brain Consortium

There are several ways to get involved in the GBC:

- Share your unique perspectives, experiences, and knowledge with members around the world to create solutions that positively impact global mental health.
- Enhance your expertise by networking with leading professionals, discovering the latest trends in brain imaging, leveraging your scientific research, and being part of a global brain network.
- Become a member of one of our working groups or create your own special interest group.

**Comment by christinerogers** [comment]
agreed this does not look amazing but the text is fine for now. 

What would make it look better on the page - a narrower frame constraining its width?

**Comment by 3design** [comment]
I've added some margin below the link items so that they are not too close together

**Comment by christinerogers** [comment]
@3design i think it's ok with the current updates and without the grey background boxes for now.  resolving.
