### ISSUE TITLE
Move repo to ACES

### ISSUE THREAD

**Issue by 3design** [3design/gbc#19]
If we want to migrate this to aces, we will need to:

- [x] add a repo on aces
- [x] add me as a collaborator
- [x] duplicate the repo to aces
- [x] set up the settings to allow the site to update using eleventy
- [x] test the site once it's built by adding some content (small change somewhere)
- [ ] point globalbrainconsotrium.org to the aces page

**Comment by christinerogers** [comment]
this is cleanup for after the launch, since the site is now on derek's repo.  

Likely worth waiting til after Faisal has another dev on staff mid-september before doing this, in case of troubleshooting / snafus
