### ISSUE TITLE
Add Vera Gross Events page

### ISSUE THREAD

**Issue by 3design** [3design/gbc#22]
- [x] Add a button on the Resources page that goes to a page dedicated to Vera Gross Events
- [x] Create a page based on the projects page to show the Vera Gross Events

**Comment by christinerogers** [comment]
super, this is fantastic.  
please change the button and the page title to `Vera Gross Lecture`. remove the arrow icon from the button 

i'll add another issue since we should do the same for the GBC Annual assembly

**Comment by christinerogers** [comment]
the url is https://3design.github.io/gbc/veragross/

**Comment by christinerogers** [comment]
closing for now.
