### ISSUE TITLE
[placeholder] add 2024 Vera gross lecture card 

### ISSUE THREAD

**Issue by christinerogers** [3design/gbc#23]
- [x] add card w info on the michael breakspear -- talk details below, 
- [x] date on the card - make it August 1 so it appears just under the GBC assembly 
- [x] take photo from the GBC program page7  (or find better res online) 
- [ ] do not show a View on Youtube button.  maybe create but comment it out if you can 
- [x] add it to the Vera Gross page so it appears at the top 

Dr. Michael Breakspear delivers the Vera Gross lecture on The Wave-Particle Theory of Brain Dynamics". This lecture is held in conjuction with the annual assembly of the Global Brain Consortium on September 6, 2024.  
Dr. Breakspear is a Psychiatrist and Neuroscientist researching the principles of
brain function in health and in mental illness. 
Professor Breakspear leads the Systems Neuroscience Group – a team of psychiatrists, physicists, psychologists and neuroimaging scientists at the University of Newcastle and Hunter Medical Research Institute, Australia.
 He uses computational modelling to study the generative processes underlying bipolar disorder, schizophrenia, dementia and in healthy ageing.

**Comment by 3design** [comment]
Added card to both news & events, as well as vera gross page. Also added new `type` called `register`. This will add the text `Register to Attend` to the button.
