### ISSUE TITLE
change favico if you can 

### ISSUE THREAD

**Issue by christinerogers** [3design/gbc#36]
see screenshot
![Screen Shot 2024-09-04 at 12 45 02 PM](https://github.com/user-attachments/assets/7c7b43c7-57f4-4a56-a737-6c7547b18d89)

icon in the tab should be gbc logo if you can override that for this repo / gh-pages branch

**Comment by 3design** [comment]
The PDF's seem to be inheriting the favicon from my 3design.github.io page (which is the test website for the BigBrain Project). I may have to rename the repo. This should theoretically remove any icon completely. I'm looking this issue up online before renaming.

**Comment by 3design** [comment]
I have moved the BBP test website to a new repo name. This should address the issue.

**Comment by 3design** [comment]
![Screen Shot 2024-09-05 at 3 06 49 PM](https://github.com/user-attachments/assets/8f86a324-7312-4e4e-8e7d-2eb1b6c1c494)

**Comment by christinerogers** [comment]
super, good enough for now.  
please add a new issue to resolve this once we move to e.g. a production repo on aces

**Comment by christinerogers** [comment]
migrated this issue for followup.
