### ISSUE TITLE
Update text on index page

### ISSUE THREAD

**Issue by 3design** [3design/gbc#4]
- [ ] Top section

# Global Brain Consortium

A diverse network of brain researchers, clinicians, and institutions committed to achieving improved and more equitable health outcomes worldwide.

- [ ] Second section: Focus is on the call to action going to the News & Events page

The Global Brain Consortium is a Canada-based initiative that builds collaborative and dynamic relationships among globally-oriented health researchers, domestically as well as internationally.

Our mission is to address the challenges that need to be overcome to drive multinational collaborative efforts in support of Global Precision Brain Health by strengthening linkages between neuroscientists across borders and disciplines.

**Comment by christinerogers** [comment]
please delete the words/characters:  `is a Canada-based initiative that` and `, domestically as well as internationally`
