### ISSUE TITLE
Grammar and Spelling corrections needed 

### ISSUE THREAD

**Issue by selineriz** [3design/gbc#41]
About us part: https://3design.github.io/gbc/about/
- [x] the GBC aims to/ GBC's aim is to --> previously written as the GBC aims is to

Global EEG Norms part: https://3design.github.io/gbc/project-eegNorms/
- [ ] creating signatures to describe EEG activity--> change it to "different **ethnicities, cultures, sexes**"
- [ ] novel normative methodologies--> MEEG sources **are** more appropriate (add verb)

Malnutrition and Brain development part: https://3design.github.io/gbc/project-malnutrition/
- [x] summary part :https://3design.github.io/gbc/projects/  --> change exhance to enhance (spelling mistake)
- [x] Overview: delete "the" children--> followed children with histories of malnutrition 

CIBD part: https://3design.github.io/gbc/project-covid/
- [ ] overview--> regarding **the** long-term impacts of the pandemic
- [x] goals--> high-powered (hyphen needed)

Child and Adolescent Brain Development part: https://3design.github.io/gbc/projects/
- [x] The summary of this project is the same as the CIBD summary--> needs change

**Comment by christinerogers** [comment]
Thanks @selineriz -- good start. 
@3design please get started on the ones I've ticked, I need to look at the rest more closely, plus:
* fix the 'Colunmbia' typo on the Global EEG norms project page 
* please link your commit here for @selineriz to look over

**Comment by christinerogers** [comment]
hi @selineriz  -- let us know tomorrow if the selected changes which were done look good to you -- since it's the first time, please take a look in both : 
* on the webpage(s) 
* using the commit link Derek provided above (see 41 above)

**Comment by selineriz** [comment]
Hi @3design @christinerogers --I've checked the corrections you made and everything looks good except for one thing on the CIBD part:
- [ ] high-powered starts with a lower case --> needs to start with "H":  https://3design.github.io/gbc/project-covid/

**Comment by christinerogers** [comment]
thanks selin - @3design i [ticked the checkbox](https://github.com/3design/gbc/issues/41#issuecomment-2346215221) to give the green light, go for it   

@selineriz  we are finding many things, so when you have fresh eyes a slow moment next week please look over the site again, I'm sure you'll find a few things further that readers will trip on

**Comment by selineriz** [comment]
@christinerogers yes sure I'll check again

**Comment by christinerogers** [comment]
selin has done a last check and it's good to go.  I'll do a last look and will merge.

**Comment by christinerogers** [comment]
resolving this issue since Selin has checked that these changes were made and look ok.
