### ISSUE TITLE
[global eeg norms Project page] fix to 1 sentence

### ISSUE THREAD

**Issue by christinerogers** [3design/gbc#42]
one small sentence to replace : 
https://github.com/3design/gbc/blob/main/src/project-eegNorms.njk#L62

Create “qEEG signature” descriptors of the EEG spectra maturation, in a wide range of age and a narrow frequency range, for large populations, which take into consideration different ethnicity, culture, sex and other socio-economical indices.

change to: 

Create “qEEG signature” descriptors of EEG spectra maturation for a narrow frequency range across ages in large populations, examining factors such as ethnicity, culture, sex and other socio-economical indices.

reviewed with @selineriz pls re-review

**Comment by selineriz** [comment]
looks good @christinerogers I'll keep looking
