### ISSUE TITLE
Update text on Network page

### ISSUE THREAD

**Issue by 3design** [3design/gbc#8]
- [ ] The headline can be updated for this page

# Our Network

The Global Brain Consortium is made up of experts dedicated to addressing the challenges that need to be overcome to drive multinational collaborative efforts in support of Global Precision Brain Health.

- [ ]  We can add job titles and/or links to the profiles (optional)

**Comment by christinerogers** [comment]
Please repeat the text (also on the front page) as the sub-headline here: 

> A diverse network of brain researchers, clinicians, and institutions committed to achieving improved and more equitable health outcomes worldwide.

**Comment by christinerogers** [comment]
Please update the headline to : 

A diverse network of brain researchers, clinicians, and institutions committed to achieving improved and more equitable health outcomes worldwide.

(Yes it repeats from the front page but i think that's ok for now )
